- .circleci/config.yml
- .editorconfig
- .eslintrc.json
- package.json
- src/course-name.html
- src/entity-mixin.html
- src/entity-store.html
@dbatiste could you enable circle ci for this repo?
> Add circle ci config

- src/link/auth-link.html
- src/link/link-sw.js
- src/my-view1.html
It just requires service workers to be supported. There are fallbacks that use dataURLs and the File APIs available, but we can worry about that later.
> Add d2l-auth-link

- src/siren-action-mixin.html
ping @cgalvind2l this fixes 405 errors in the Acknowledge/Dismiss actions
> Fix siren-action-mixin typo

- bower.json
- data/items.js
- src/entity-mixin.html
- src/entity-store.html
- src/my-app.html
- src/my-view1.html
TODO:
* Make components that grab and render lists of entities
FIXME:
* Currently loads hard coded orgunits (6606, 6609, 6613, 6614)
> It's a wrap! pt1 - Allow passing of token

- .eslintrc.json
- index.html
- src/my-app.html
Just some really basic performance mark timing and a listener for "paint" and "longtask" events. More detailed marks and logging coming.
> Basic performance marks

- data/items.js
- src/my-view1.html
> Use updates rel for updates card

- src/my-app.html
- src/my-view1.html
to allow the other views to specify their own entrypoint/token and to simplify my-app.html
> Split out token/entrypoint selection from my-app element

- src/discussions/discussions-topic-post-item.html
- src/discussions/discussions-topic-post-reply-item.html
- src/my-view1.html
- src/shared-styles.html
> Reset token that I broke

- src/courses/courses-card.html
- src/courses/enrollment-item.html
Since that's more accurately what it is; I was getting confused :sob:
> Rename courses-list to enrollment-item

- polymer.json
- src/courses/course-item.html
- src/my-app.html
- src/my-course-page.html
Nothing on the page at the moment, and it doesn't do anything with the passed in organization href, but... it's there!
> Add my-course-page and go to it when a course is clicked

- src/my-app.html
- src/my-course-page.html
> Course page do more stuff

- src/my-login-page.html
Note: I think when I ran the linter with fix it may have adjusted the spacing I didn't change that much
> login with the oauth token service

- src/activities/user-activity-usage-list.html
@cgalvind2l This adds the whole month of activities for the activities list; working on calendar next.
> Get activities for the whole month

- package.json
- src/activities/activity-card.js
- src/awards/award-item.js
- src/calendar/calendar-week.js
- src/discussions/discussions-topic-post-list.js
- src/entity-mixin.js
- src/my-view2.js
- src/my-view404.js
* Convert a few simple elements as an example
> Modify entity-mixin to work with lit-element

- src/entity-store.js
- src/my-app.js
- src/my-virtual-notebook.js
* Added a blank page with a header for the virtual notebook.
* Can navigate from hamburger menu.
* Loads notes
> Adding a page for the virtual notebook

- src/entity-store.js
- src/my-app-main-page.js
- src/my-welcome-page.js
- src/notes/note-create.js
- src/notes/note.js
- src/notes/notes-by-resource.js
- src/notes/notes-count.js
- src/siren-action-mixin.js
Trello: https://trello.com/c/kknI15Ok/27-use-add-note-functionality-in-note-create-component
> Use add in note action in note create

- src/my-app.js
- src/my-virtual-notebook.js
Ability to sort notes in the notebook.
Seems like https://github.com/Brightspace/notes-as-a-service/pull/7 didn't deploy properly so need to wait for that first for this to work.
> Option to sort by asc or desc date

- src/entity-store.js
- src/my-login-page.js
Replaced websockets with long polling. Notifications are also received if a user goes offline and comes back.
> Restore push notifications

- src/my-virtual-notebook.js
- src/notes/note-create-self.js
- src/notes/note.js
- src/notes/notes-count.js
- src/notes/notes-shim.js
- src/shared-styles.js
- Might have overdone the CSS a little bit, epecially with the font family that borders into a Comic-sans esque type. Playing with making it look like a note really
- Changed the colour into the real stick note yellow
- Clickable count to show notes and the ability to add a note
> Note count click see add notes

- src/my-virtual-notebook.js
- src/notes/note-create-self.js
Trello: https://trello.com/c/DmXs4jCJ/6-create-note-with-no-resource-context
- I hummed and ha'd about whether to create a new component or add an optional argument to note-create and just leave out the subject field when posting. To avoid some code duplication, but I talked myself out of it. I can totally open to doing it that way as well
- Moving around some UI on Virtual Notebook Page
> Adding new component to write notes to self

- package-lock.json
- src/entity-mixin.js
- src/my-virtual-notebook.js
- src/notes/contextual-note.js
- src/redux-connector.js
> intline content'
